### PR TITLE
Translation to Spanish from Spain (es_ES)

### PR DESCRIPTION
**Pull request by mirenbz**
I've decided to do this translation because I am planning to use git-it with my students and the Colombian translation uses some terms and structures that could add difficulty to them.

This translation is based on the Colombian translation to Spanish (thanks @camilomontoyau!) but adds the following modifications:

- use of most widespread terms in Spain (_ordenador_ instead of _computadora_ or the avoidance of _halar_ which is not understood in Spain)
- adaptation and correction of some mistakes in punctuation
- use of non-sexist language

I will try to make my own build to send to students (which I will need to do this week!), but I wanted to contribute it here at the same time.

### CODE REVIEW

**Comment by camilomontoyau** [comment]
awesome @mberasategi 
if you need some help don't hesitate to ask for it!!!

**Comment by mberasategi** [comment]
I forgot to add es_ES to the list of languages in the README file, which is now done. Is there anything left I need to do before this is suitable for merging? Thanks!

**Comment by jlord** [comment]
Awesome, thanks so much!!! I'll get it reviewed today 👍

**Comment by jlord** [comment]
This looks good! Thanks soooooo much! 🇪🇸

**Comment by jlord** [comment]
New release ✨

**Comment by mberasategi** [comment]
👏

**Pull request merged**
