### PR TITLE
Make use of ES6

### LINKED ISSUE #7: Open External Links Externally...
Make sure to have all links that aren't Git-it (that link to other, real websites) open a new browser window a la:

```js
require('shell').openExternal('http://github.com/jlord/git-it-electron')
```

### LINKED ISSUE #16: Remembering state
Load completed state and selected directories/files. They should be saved to `data.json`

### LINKED ISSUE #20: Specify user{Data, Cache} directories
Currently You have not specified userData and userCache directories in the browser (main) process. Which means that default `Electron Default App` dirs are used.
Example: https://github.com/steelbrain/Brauser/blob/master/Browser/Main.js#L17

### PR DESCRIPTION
**Pull request by steelbrain**
:rotating_light: A work in progress :rotating_light:
- [x] Make the main.js file human readable
- [x] Merge other-menu.js and darwin-menu.js into one (also make use of module.parent.exports instead of exporting a function and calling that function)
- [x] Set app{Data, Cache} dirs in main.js (fixes #20)
- [x] Set a friendly name for programs like `ps`
- [x] Make use of remote module in the renderer side
- [x] Open external links externally (fixes #7)
- [x] All while not using commas (I have observed that it's a personal taste of @jlord )
- [x] Create a `Progress` class that provides a nice API around challenges. (fix #16)
- [x] Rewrite all verify modules to be human readable
- [x] Remove the IPC thingy and call dialog directly
- [x] use localStorage instead of data.json
- [x] set Favicon as app icon

... and other stuff I can't think of right now

### CODE REVIEW

**Comment by jlord** [comment]
:wave: Hi! I super appreciate your helping out on this project! 

This, however, is already a fairly large pull request with a scope of impact rather larger than I'd like to merge in one go. Also, my use of callbacks and no ES6 is quite intentional.

I think it would be best to first open an Issue to discuss structural changes (other than promises/ES6/syntax which won't be changing in this project) and smaller PRs for individual open Issue fixes :sparkles: 

I'll get a contributing doc up soon to make some of these things more clear :+1:

**Comment by steelbrain** [comment]
Note: This PR is 100% working with no bugs.

> Also, my use of callbacks and no ES6 is quite intentional.

Note: Electron always ships with the latest chrome which means that you don't have to worry about cross-browser stuff and stuff always works in it.

Anyways, I would love to hear why though.

> smaller PRs for individual open Issue fixes

smaller PRs as in the PRs that add a missing favicon or like the ones that replace data.json with Progress class?

**Comment by maxogden** [comment]
@steelbrain in this PR you rewrote a bunch of code and converted into your personal style for no good reason other than you think it is better, without consulting the maintainer first for a 'patch welcome'. Generally it's a good idea to open an issue for stylistic changes. I try to put that info in my contributing files, e.g. [here](https://github.com/moose-team/friends/blob/master/CONTRIBUTING.md#contributing-guidelines) that says 'Before spending lots of time on something, ask for feedback on your idea first!'

Not everyone has the same coding style or preferences, and nobody likes it when someone wastes a bunch of time making opinionated changes without checking first. I've seen tons of pull requests in open source that are like this or e.g. unsolicited rewrite entire projects in CoffeeScript that end up being wastes of time for all parties involved because not everyone makes the same code style choices.

In addition, when a project isn't even released/announced yet I make an extra effort to check with the author first about the above issues.

**Comment by steelbrain** [comment]
@maxogden Yep, I admit it ^_^ I should've discussed it first.
I am not a professional kinda guy, just a 16 years old student, so Yeah, I am gonna make mistakes :D

**Pull request closed without merging**
