### PR TITLE
Remember selected folder between challenges

### LINKED ISSUE #47: Save Directory
Since the user will be using the same directory for most of the challenges, we should save that so they don't have to re-select it every time.

### PR DESCRIPTION
**Pull request by stdavis**
Closes #47 

I'm not sure if this is what you had in mind or not. Either way it was a fun introduction to an electron app.

Thanks for the awesome project! I plan on using it in an intro to GitHub workshop that I'm teaching at a conference in Utah in a few weeks.

### CODE REVIEW

**Comment by jlord** [comment]
Wow, excited about this! Have had a busy week or so but will check this out 🔜 !

**Comment by stdavis** [comment]
I don't know if it's possible but it would be great if you got to this before my workshop on the 13th. This would be a great story to tell to introduce pull requests. If it doesn't happen, no big deal.

**Comment by jlord** [comment]
I was able to checkout the branch today and there are a few things that don't work out, like in a few places it assumes everything inside of `user-data.json` is a challenge and so this new object causes errors. 

I'm also thinking it should be cleared out when they get to the challenge that uses a different repository, so that it's not confusing. 

I started a branch off of yours but my scope kept growing and now I think perhaps it should just be two data files instead of the one. I'll try and put something together soon (am technically on vacation now so we'll see 😁).

**Comment by jlord** [comment]
Hi @stdavis! I'm going to close this PR out here, but I've incorporated and expanded on your commit into #132  ✨ 

Thanks so much for the impetus in getting this going!

**Comment by stdavis** [comment]
👍 I used this project in a workshop that I taught this morning and it worked great. Thanks!

**Pull request closed without merging**
