### PR TITLE
Translate to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by lubien**

### CODE REVIEW

**Comment by jlord** [comment]
Thanks so much for working on this!

There are a couple of things I noticed after a quick look at this:

- The images you updated (so awesome!) aren't being used
 - screen shot 2016-09-01 at 3 23 33 pm
- The style will need to be fixed on the language menu
 - screen shot 2016-09-01 at 3 23 28 pm
- The button on the home page doesn't take you to the translated page (if you change the language on the front page) (this is likely my bug)

The last two I will look into fixing myself but maybe you can take a look at the images one?

**Comment by lubien** [comment]
Sure. I'll do it

**Comment by lubien** [comment]
Built pr-br challenges once again and now it's ok, but one image is not translated. I've called @rian-vergara (images translator) already

**Comment by lubien** [comment]
Done ^^

**Comment by jlord** [comment]
Thank you!! 🎉

**Comment by lubien** [comment]
:D

**Pull request merged**
