### PR TITLE
Updated clone.png

### PR DESCRIPTION
**Pull request by danieldrasdo**
Updated the clone.png to better illustrate pulling from someone else's repo.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@danieldrasdo I think the old one was correct: pulling is just getting the stuff from remote. According to this representation, you probably cannot push into someone else repo because you don't have permissions, but you can pull. :thought_balloon: 

**your fork** :arrow_left: :arrow_right: **local repo** (pull/clone and push)
**original repo** :arrow_right: **local repo** (clone/pull, as long you don't have write permissions)

**Comment by danieldrasdo** [comment]
I agree with you, which is why the arrow 'pushing' (going up) to an original repo was removed. Sorry, I'm not quite sure I see what you disagree with. Can you please clarify? The reason being, I sent a pull request to the git-it repo that was accepted and merged, so I want to make sure I didn't do anything that will cause confusion.

**Comment by jlord** [comment]
The updated image in this PR removes the push arrow because you might not be able to push to a repo that you don't have permission to.

I need to update the "to" still left in the words, but if I understand your comment @IonicaBizau, this PR does show what you suggest.

**Comment by IonicaBizau** [comment]
@danieldrasdo @jlord Ahhh, I was playing with the image diff swipping and I guessed the arrow was added, not removed. Totally agree, sorry for confusion. :joy:

**Comment by danieldrasdo** [comment]
@IonicaBizau @jlord, thanks everybody!

**Comment by IonicaBizau** [comment]
@danieldrasdo :+1:

**Comment by zeke** [comment]
> I guessed the arrow was added, not removed.

Same confusion here.

**Pull request merged**
