### PR TITLE
flatten packages in build process

### LINKED ISSUE #62: Flatten node_modules
During the Tokyo Patchwork, we ran into an issue on one attendee's machine where they couldn't extract the zip file because of [the Windows MAX_PATH issue](https://github.com/nodejs/node-v0.x-archive/issues/6960).

The longest path in the zip file is 214 characters long. Since `MAX_PATH` on Windows is 260, this means extracting Git-it in a target directory which has a path longer than 46 characters will fail.

When we extracted the Git-it zip directly under the `C:\`, the extraction worked and the app runs.

Would it be possible to use something like [npm-flatten](https://www.npmjs.com/package/npm-flatten) to flatten the node_modules directories before building the Windows zip?

cc @shiftkey @jlord

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #62 

- [x] added some docs for the packaging process
- [x] flatten as part of building assets
- [x] ignore generated folders 

@muan @jlord if there's a more appropriate place in the build scripts to run this step, let me know.

Also, any other feedback you might have would be greatly appreciated. :boom: :camel: :tada:

### CODE REVIEW

**Comment by shiftkey** [comment]
For reference, the net effect of this PR is that the longest relative path under `node_modules` (292 characters):

>node_modules/standard/node_modules/standard-format/node_modules/esformatter-jsx/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/yargs/node_modules/cliui/node_modules/center-align/node_modules/align-text/node_modules/kind-of/node_modules/is-buffer/test/basic.js

is now just 159 characters:

> node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Mantle.framework/Versions/A/Headers/NSValueTransformer+MTLPredefinedTransformerAdditions.h

While we have a `MAX_PATH` of 260 characters on Windows, this still gives us a lot of extra room to work with when deploying the app.

**Comment by paulcbetts** [comment]
An easier way to do this is just to require npm 3.X which will get you most of the way there for free

**Comment by shiftkey** [comment]
@paulcbetts this definitely interests me, but I'll defer to @muan and @jlord on whether they are (or want to) make the jump...

**Comment by jlord** [comment]
So happy! Thank you @shiftkey!

@paulcbetts I had not been paying attention and did not realize this fun fact! Just :eyes: it on the [changelog](https://github.com/npm/npm/releases/tag/v3.0.0) though. Nice!

> Flat, flat, flat!

> Your dependencies will now be installed maximally flat. Insofar as is possible, all of your dependencies, and their dependencies, and THEIR dependencies will be installed in your project's node_modules folder with no nesting. You'll only see modules nested underneath one another when two (or more) modules have conflicting dependencies.

I'll update my npm and give it a go. I think it would be fine to offer up this way for people who haven't updated (it's still pre-release) and explain the other way to just build as normal but using npm@3.

**Comment by paulcbetts** [comment]
@jlord Ya, npm 3 is The Solution for long path problems on Windows, and we haven't had any problems with the upgrade for Slack

**Comment by jlord** [comment]
Gonna merge this since I'll provide this option anyways and am gonna spend some time on this repo over the holidays and add the npm 3 option, too :christmas_tree: 

Thanks! :100:

**Pull request merged**
