### PR TITLE
Translated into :jp: language

### PR DESCRIPTION
**Pull request by ikeike443**
Hi @jlord,

This is the PR that translate into :jp: completely which was used for the [patchwork](http://patchwork.github.io/)s held in Kobe, Kyoto, Tokyo.

Could you please check it and merge it if you don't see any problems on it?

Thanks.

(Sorry about  #90, which was just a mistaken..., this is the correct one.)

### CODE REVIEW

**Comment by ikeike443** [comment]
cc @muan

**Comment by jlord** [comment]
Awesome, this is fantastic! 

@dice should this supersede #79?

**Comment by dice** [comment]
@jlord absolutely, I'll just close #79

**Comment by ikeike443** [comment]
@jlord Fixed the conflicts. :smile:

**Comment by jlord** [comment]
Oh, fantastic, thanks so, so much!

I'm gonna spend some of the holidays getting back into this and hopefully get it out of a beta state :sparkles:

**Pull request merged**
