### PR TITLE
Improve locale support

### PR DESCRIPTION
**Pull request by vongola12324**
Hi, this is the first part of PR which splited from PR #152 and based on #156 .

This PR contains these updates:
- locale support
- update contributing

First, I found that all translation pages is storage at root folder, using challenges-contents-(locale)as folders name. It will have lots of folders under your root folder when adding many locale support, that might make contributions maintain project hardly. So, I wrote a locale.js to fix the locale issue, and all locale files should be placed in resources/contents.

After I split the PR, files changed is still more than 100 files even except those files changed in #156 .
Because of moving files from old place to new folder, it make about 60 files changed.
If I didn't remove those files which generated by `npm run build-all`, this PR will be larger, because those files will move to built folder. Also, because the structure of project is changed, path in all javascript files need to change, So, that's the reason why there are so much files been changed.

Here are the folder changed:
- `challenge-content-<lang>` -> `resources\contents\<lang>\challenges`
- `page-content-<lang>` -> `resources\contents\<lang>\pages`
- `layouts` -> `resources\layouts\`
- `challenges-<lang>` -> `built\<lang>\challenges`
- `pages-<lang>` -> `built\<lang>\pages`

Hope these changes will be useful to make Git-it better.

Vongola

### CODE REVIEW

**Comment by vongola12324** [comment]
Hi, 
It have been two month ago.It seem that you skip this PR. 😢 
Did I do something wrong on this PR? If true, please let me know, and I will fix it.
I thinks this improvement would let the translators more convenient in the translation.

**Comment by jlord** [comment]
@vongola12324 Hi! Sorry for the delay, unfortunately I haven't had the time to put into this project right now which is why this PR still sits.

It is still quite a large PR and has to do with parts of Git-it that I want to to sit and re-think (and possibly re-write) so it will take time to review and consider how it fits into the future of Git-it.

I reallllllly appreciate your contribution 🙏 and do plan to get to this when I am able to give it the time.

**Comment by jlord** [comment]
Okie dokie! Again, thanks so much for all this help!

I've merged your other PR and have merged a few more with additional translations. So this one has some conflicts now but I'm going to walk 🚶 through them and do the manual merge. Excited for this update!

**Comment by jlord** [comment]
🎉 Thanks again, this was great!

I'm sure there are some little broken pieces in here from my merge (and trying to get the other languages that have since been added set up correctly) but I'll clean it up as I run through it more carefully before the next release.

🍰 💯

**Comment by vongola12324** [comment]
🎉  Wow!!
I love git-it, and I'm happy to see this PR is merged.
If there is anything I can help, please tell me.

Best wishes for the holidays and happiness throughout the New Year.  :

**Pull request merged**
